on:
    workflow_dispatch:
    schedule:
        - cron: '0 */6 * * *'

jobs:
    drive_2:
        runs-on: ubuntu-latest
        steps:
            - name: rclone
              uses: wei/rclone@v1
              env:
                  RCLONE_CONF: ${{ secrets.RCLONE }}
              with:
                  args: sync drive_1:/ drive_2:/ --fast-list --tpslimit-burst=16 --ignore-errors --stats=30s --max-backlog=2000000 --ignore-case --size-only --no-update-modtime --drive-chunk-size=256M --drive-use-trash=false --drive-server-side-across-configs=true --drive-stop-on-upload-limit --drive-skip-gdocs --drive-acknowledge-abuse --timeout=10s --tpslimit=4 -q

    drive_3:
        runs-on: ubuntu-latest
        steps:
            - name: rclone
              uses: wei/rclone@v1
              env:
                  RCLONE_CONF: ${{ secrets.RCLONE }}
              with:
                  args: sync drive_1:/ drive_3:/ --fast-list --tpslimit-burst=16 --ignore-errors --stats=30s --max-backlog=2000000 --ignore-case --size-only --no-update-modtime --drive-chunk-size=256M --drive-use-trash=false --drive-server-side-across-configs=true --drive-stop-on-upload-limit --drive-skip-gdocs --drive-acknowledge-abuse --timeout=10s --tpslimit=4 -q

    onedrive:
        runs-on: ubuntu-latest
        steps:
            - name: rclone
              uses: wei/rclone@v1
              env:
                  RCLONE_CONF: ${{ secrets.RCLONE }}
              with:
                  args: sync drive_1:/ onedrive:/ --fast-list --tpslimit-burst=16 --ignore-errors --stats=30s --max-backlog=2000000 --ignore-case --size-only --no-update-modtime --drive-chunk-size=256M --drive-use-trash=false --drive-server-side-across-configs=true --drive-stop-on-upload-limit --drive-skip-gdocs --drive-acknowledge-abuse --timeout=10s --tpslimit=4 -q
